In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/asche0001111/ironhack-project-3/main/drug_consumption.csv")

In [3]:
df.head()

,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,...,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,Semer,VSA
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,...,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL2,CL0,CL0
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,...,CL4,CL0,CL2,CL0,CL2,CL3,CL0,CL4,CL0,CL0
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,...,CL0,CL0,CL0,CL0,CL0,CL0,CL1,CL0,CL0,CL0
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,...,CL0,CL0,CL2,CL0,CL0,CL0,CL0,CL2,CL0,CL0
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,...,CL1,CL0,CL0,CL1,CL0,CL0,CL2,CL2,CL0,CL0

In [4]:
#check shape

In [5]:
df.shape

(1885, 32)

In [6]:
df.info

<bound method DataFrame.info of         ID      Age   Gender  Education  Country  Ethnicity   Nscore   Escore  \
0        1  0.49788  0.48246   -0.05921  0.96082    0.12600  0.31287 -0.57545
1        2 -0.07854 -0.48246    1.98437  0.96082   -0.31685 -0.67825  1.93886
2        3  0.49788 -0.48246   -0.05921  0.96082   -0.31685 -0.46725  0.80523
3        4 -0.95197  0.48246    1.16365  0.96082   -0.31685 -0.14882 -0.80615
4        5  0.49788  0.48246    1.98437  0.96082   -0.31685  0.73545 -1.63340
...    ...      ...      ...        ...      ...        ...      ...      ...
1880  1884 -0.95197  0.48246   -0.61113 -0.57009   -0.31685 -1.19430  1.74091
1881  1885 -0.95197 -0.48246   -0.61113 -0.57009   -0.31685 -0.24649  1.74091
1882  1886 -0.07854  0.48246    0.45468 -0.57009   -0.31685  1.13281 -1.37639
1883  1887 -0.95197  0.48246   -0.61113 -0.57009   -0.31685  0.91093 -1.92173
1884  1888 -0.95197 -0.48246   -0.61113  0.21128   -0.31685 -0.46725  2.12700

       Oscore   Ascore  ...  Ecstasy  Heroin  Ketamine Legalh  LSD Meth  \
0    -0.58331 -0.91699  ...      CL0     CL0       CL0    CL0  CL0  CL0
1     1.43533  0.76096  ...      CL4     CL0       CL2    CL0  CL2  CL3
2    -0.84732 -1.62090  ...      CL0     CL0       CL0    CL0  CL0  CL0
3    -0.01928  0.59042  ...      CL0     CL0       CL2    CL0  CL0  CL0
4    -0.45174 -0.30172  ...      CL1     CL0       CL0    CL1  CL0  CL0
...       ...      ...  ...      ...     ...       ...    ...  ...  ...
1880  1.88511  0.76096  ...      CL0     CL0       CL0    CL3  CL3  CL0
1881  0.58331  0.76096  ...      CL2     CL0       CL0    CL3  CL5  CL4
1882 -1.27553 -1.77200  ...      CL4     CL0       CL2    CL0  CL2  CL0
1883  0.29338 -1.62090  ...      CL3     CL0       CL0    CL3  CL3  CL0
1884  1.65653  1.11406  ...      CL3     CL0       CL0    CL3  CL3  CL0

     Mushrooms Nicotine Semer  VSA
0          CL0      CL2   CL0  CL0
1          CL0      CL4   CL0  CL0
2          CL1      CL0   CL0  CL0
3          CL0      CL2   CL0  CL0
4          CL2      CL2   CL0  CL0
...        ...      ...   ...  ...
1880       CL0      CL0   CL0  CL5
1881       CL4      CL5   CL0  CL0
1882       CL2      CL6   CL0  CL0
1883       CL3      CL4   CL0  CL0
1884       CL3      CL6   CL0  CL2

[1885 rows x 32 columns]>

In [7]:
#checking for nulls

In [8]:
df.isnull().sum()

ID           0
Age          0
Gender       0
Education    0
Country      0
Ethnicity    0
Nscore       0
Escore       0
Oscore       0
Ascore       0
Cscore       0
Impulsive    0
SS           0
Alcohol      0
Amphet       0
Amyl         0
Benzos       0
Caff         0
Cannabis     0
Choc         0
Coke         0
Crack        0
Ecstasy      0
Heroin       0
Ketamine     0
Legalh       0
LSD          0
Meth         0
Mushrooms    0
Nicotine     0
Semer        0
VSA          0
dtype: int64

In [9]:
drug_col = ["Alcohol", "Amphet", "Amyl", "Benzos", "Caff", "Cannabis", "Choc", "Coke", "Crack", "Ecstasy", "Heroin", "Ketamine", "Legalh", "LSD", "Meth", "Mushrooms", "Nicotine", "Semer", "VSA"]

In [10]:
for col in drug_col:
    df[col] = df[col].str.extract(r'(\d+)')

In [11]:
df

,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,...,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,Semer,VSA
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,...,0,0,0,0,0,0,0,2,0,0
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,...,4,0,2,0,2,3,0,4,0,0
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,...,0,0,0,0,0,0,1,0,0,0
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,...,0,0,2,0,0,0,0,2,0,0
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,...,1,0,0,1,0,0,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,1884,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,...,0,0,0,3,3,0,0,0,0,5
1881,1885,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,...,2,0,0,3,5,4,4,5,0,0
1882,1886,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,...,4,0,2,0,2,0,2,6,0,0
1883,1887,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,...,3,0,0,3,3,0,3,4,0,0
1884,1888,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,...,3,0,0,3,3,0,3,6,0,2

In [12]:
df.dtypes

ID             int64
Age          float64
Gender       float64
Education    float64
Country      float64
Ethnicity    float64
Nscore       float64
Escore       float64
Oscore       float64
Ascore       float64
Cscore       float64
Impulsive    float64
SS           float64
Alcohol       object
Amphet        object
Amyl          object
Benzos        object
Caff          object
Cannabis      object
Choc          object
Coke          object
Crack         object
Ecstasy       object
Heroin        object
Ketamine      object
Legalh        object
LSD           object
Meth          object
Mushrooms     object
Nicotine      object
Semer         object
VSA           object
dtype: object

### drug bins:

soft (alcohol, caffeine, cannabis, nicotine)
prescription (amphetamines, benzodiazapenes)
stimulants (amphetamines, caffeine, cocaine, crack, ecstasy, meth)
depressants (alcohol, benzos, heroin, ketamine)
psychedelics (LSD, mushrooms, ketamine?)
legal (alcohol, caffeine, nicotine, amyl, legal highs, VSA)
illegal (cocaine, crack, ecstasy, heroin, LSD, meth, mushrooms)
inhalants (amyl, VSA)
drop whole row: semer
drop col: chocolate

In [13]:
df["Soft"] = None
def calculate_soft(df):
    for index, row in df.iterrows():
        alcohol = int(row["Alcohol"])
        caff = int(row["Caff"])
        cannabis = int(row["Cannabis"])
        nicotine = int(row["Nicotine"])
        df.loc[index, "Soft"] = max(alcohol, caff, cannabis, nicotine)

calculate_soft(df)

In [14]:
df

,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,...,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,Semer,VSA,Soft
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,...,0,0,0,0,0,0,2,0,0,6
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,...,0,2,0,2,3,0,4,0,0,6
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,...,0,0,0,0,0,1,0,0,0,6
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,...,0,2,0,0,0,0,2,0,0,5
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,...,0,0,1,0,0,2,2,0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,1884,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,...,0,0,3,3,0,0,0,0,5,5
1881,1885,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,...,0,0,3,5,4,4,5,0,0,5
1882,1886,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,...,0,2,0,2,0,2,6,0,0,6
1883,1887,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,...,0,0,3,3,0,3,4,0,0,6
1884,1888,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,...,0,0,3,3,0,3,6,0,2,6

In [15]:
df["Soft"].value_counts()

Soft
6    1621
5     209
4      33
3      14
1       6
0       2
Name: count, dtype: int64

In [16]:
pd.set_option('display.max_columns', None)

In [17]:
df["Prescription"] = None
def calculate_prescription(df):
    for index, row in df.iterrows():
        amphet = int(row["Amphet"])
        benzos = int(row["Benzos"])
        df.loc[index, "Prescription"] = max(amphet, benzos)

calculate_prescription(df)

In [18]:
df

,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Alcohol,Amphet,Amyl,Benzos,Caff,Cannabis,Choc,Coke,Crack,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,Semer,VSA,Soft,Prescription
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084,5,2,0,2,6,0,5,0,0,0,0,0,0,0,0,0,2,0,0,6,2
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,-0.14277,-0.71126,-0.21575,5,2,2,0,6,4,6,3,0,4,0,2,0,2,3,0,4,0,0,6,2
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,-1.37983,0.40148,6,0,0,0,6,3,4,0,0,0,0,0,0,0,0,1,0,0,0,6,0
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,0.58489,-1.37983,-1.18084,4,0,0,3,5,2,4,2,0,0,0,2,0,0,0,0,2,0,0,5,3
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,1.30612,-0.21712,-0.21575,4,1,1,0,6,3,6,0,0,1,0,0,1,0,0,2,2,0,0,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,1884,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,-1.13788,0.88113,1.92173,5,0,0,0,4,5,4,0,0,0,0,0,3,3,0,0,0,0,5,5,0
1881,1885,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,-1.51840,0.88113,0.76540,5,0,0,0,5,3,4,0,0,2,0,0,3,5,4,4,5,0,0,5,0
1882,1886,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,-1.38502,0.52975,-0.52593,4,6,5,5,6,6,6,4,0,4,0,2,0,2,0,2,6,0,0,6,6
1883,1887,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,-2.57309,1.29221,1.22470,5,0,0,0,6,6,5,0,0,3,0,0,3,3,0,3,4,0,0,6,0
1884,1888,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,0.41594,0.88113,1.22470,4,3,0,3,6,3,6,3,0,3,0,0,3,3,0,3,6,0,2,6,3

In [19]:
df["Prescription"].value_counts()

Prescription
0    732
3    276
2    274
1    188
6    173
4    129
5    113
Name: count, dtype: int64

In [20]:
df["Stims"] = None
def calculate_stims(df):
    for index, row in df.iterrows():
        amphet = int(row["Amphet"])
        caff = int(row["Caff"])
        coke = int(row["Coke"])
        crack = int(row["Crack"])
        xtc = int(row["Ecstasy"])
        meth = int(row["Meth"])
        df.loc[index, "Stims"] = max(amphet, caff, coke, crack, xtc, meth)

calculate_stims(df)

In [21]:
df

,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Alcohol,Amphet,Amyl,Benzos,Caff,Cannabis,Choc,Coke,Crack,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,Semer,VSA,Soft,Prescription,Stims
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084,5,2,0,2,6,0,5,0,0,0,0,0,0,0,0,0,2,0,0,6,2,6
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,-0.14277,-0.71126,-0.21575,5,2,2,0,6,4,6,3,0,4,0,2,0,2,3,0,4,0,0,6,2,6
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,-1.37983,0.40148,6,0,0,0,6,3,4,0,0,0,0,0,0,0,0,1,0,0,0,6,0,6
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,0.58489,-1.37983,-1.18084,4,0,0,3,5,2,4,2,0,0,0,2,0,0,0,0,2,0,0,5,3,5
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,1.30612,-0.21712,-0.21575,4,1,1,0,6,3,6,0,0,1,0,0,1,0,0,2,2,0,0,6,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,1884,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,-1.13788,0.88113,1.92173,5,0,0,0,4,5,4,0,0,0,0,0,3,3,0,0,0,0,5,5,0,4
1881,1885,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,-1.51840,0.88113,0.76540,5,0,0,0,5,3,4,0,0,2,0,0,3,5,4,4,5,0,0,5,0,5
1882,1886,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,-1.38502,0.52975,-0.52593,4,6,5,5,6,6,6,4,0,4,0,2,0,2,0,2,6,0,0,6,6,6
1883,1887,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,-2.57309,1.29221,1.22470,5,0,0,0,6,6,5,0,0,3,0,0,3,3,0,3,4,0,0,6,0,6
1884,1888,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,0.41594,0.88113,1.22470,4,3,0,3,6,3,6,3,0,3,0,0,3,3,0,3,6,0,2,6,3,6

In [22]:
df["Stims"].value_counts()

Stims
6    1438
5     252
4      94
3      54
0      22
2      16
1       9
Name: count, dtype: int64

In [23]:
df["HardStims"] = None
def calculate_hstims(df):
    for index, row in df.iterrows():
        amphet = int(row["Amphet"])
        coke = int(row["Coke"])
        crack = int(row["Crack"])
        xtc = int(row["Ecstasy"])
        meth = int(row["Meth"])
        df.loc[index, "HardStims"] = max(amphet, coke, crack, xtc, meth)

calculate_hstims(df)

In [24]:
df

,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Alcohol,Amphet,Amyl,Benzos,Caff,Cannabis,Choc,Coke,Crack,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,Semer,VSA,Soft,Prescription,Stims,HardStims
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084,5,2,0,2,6,0,5,0,0,0,0,0,0,0,0,0,2,0,0,6,2,6,2
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,-0.14277,-0.71126,-0.21575,5,2,2,0,6,4,6,3,0,4,0,2,0,2,3,0,4,0,0,6,2,6,4
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,-1.37983,0.40148,6,0,0,0,6,3,4,0,0,0,0,0,0,0,0,1,0,0,0,6,0,6,0
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,0.58489,-1.37983,-1.18084,4,0,0,3,5,2,4,2,0,0,0,2,0,0,0,0,2,0,0,5,3,5,2
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,1.30612,-0.21712,-0.21575,4,1,1,0,6,3,6,0,0,1,0,0,1,0,0,2,2,0,0,6,1,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,1884,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,-1.13788,0.88113,1.92173,5,0,0,0,4,5,4,0,0,0,0,0,3,3,0,0,0,0,5,5,0,4,0
1881,1885,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,-1.51840,0.88113,0.76540,5,0,0,0,5,3,4,0,0,2,0,0,3,5,4,4,5,0,0,5,0,5,4
1882,1886,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,-1.38502,0.52975,-0.52593,4,6,5,5,6,6,6,4,0,4,0,2,0,2,0,2,6,0,0,6,6,6,6
1883,1887,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,-2.57309,1.29221,1.22470,5,0,0,0,6,6,5,0,0,3,0,0,3,3,0,3,4,0,0,6,0,6,3
1884,1888,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,0.41594,0.88113,1.22470,4,3,0,3,6,3,6,3,0,3,0,0,3,3,0,3,6,0,2,6,3,6,3

In [25]:
df["HardStims"].value_counts()

HardStims
0    711
3    276
2    215
6    193
4    192
1    155
5    143
Name: count, dtype: int64

In [26]:
df["Downers"] = None
def calculate_downers(df):
    for index, row in df.iterrows():
        alc = int(row["Alcohol"])
        benzos = int(row["Benzos"])
        h = int(row["Heroin"])
        k = int(row["Ketamine"])
        df.loc[index, "Downers"] = max(alc, benzos, h, k)

calculate_downers(df)

In [27]:
df["Downers"].value_counts()

Downers
5    759
6    583
4    269
3    170
2     57
0     25
1     22
Name: count, dtype: int64

In [28]:
df["HardDowners"] = None
def calculate_hdowners(df):
    for index, row in df.iterrows():
        benzos = int(row["Benzos"])
        h = int(row["Heroin"])
        k = int(row["Ketamine"])
        df.loc[index, "HardDowners"] = max(benzos, h, k)

calculate_hdowners(df)

In [29]:
df["HardDowners"].value_counts()

HardDowners
0    890
3    265
2    247
4    143
1    119
5    114
6    107
Name: count, dtype: int64

In [30]:
df["Psychs"] = None
def calculate_psychs(df):
    for index, row in df.iterrows():
        lsd = int(row["LSD"])
        shrooms = int(row["Mushrooms"])
        k = int(row["Ketamine"])
        df.loc[index, "Psychs"] = max(lsd, shrooms, k)

calculate_psychs(df)

In [31]:
df["Psychs"].value_counts()

Psychs
0    824
3    288
1    249
2    233
4    160
5    111
6     20
Name: count, dtype: int64

In [32]:
#legal (alcohol, caffeine, nicotine, amyl, legal highs, VSA)
df["Legal"] = None
def calculate_legal(df):
    for index, row in df.iterrows():
        alc = int(row["Alcohol"])
        caff = int(row["Caff"])
        nic = int(row["Nicotine"])
        amyl = int(row["Amyl"])
        lh = int(row["Legalh"])
        vsa = int(row["VSA"])
        df.loc[index, "Legal"] = max(alc, caff, nic, amyl, lh, vsa)

calculate_legal(df)

In [33]:
df["Legal"].value_counts()

Legal
6    1578
5     237
4      40
3      19
1       6
2       3
0       2
Name: count, dtype: int64

In [34]:
#illegal (cocaine, crack, ecstasy, heroin, LSD, meth, mushrooms)

df["Illegal"] = None
def calculate_illegal(df):
    for index, row in df.iterrows():
        c = int(row["Coke"])
        crack = int(row["Crack"])
        xtc = int(row["Ecstasy"])
        h = int(row["Heroin"])
        lsd = int(row["LSD"])
        meth = int(row["Meth"])
        shrooms = int(row["Mushrooms"])
        df.loc[index, "Illegal"] = max(c, crack, xtc, h, lsd, meth, shrooms)

calculate_illegal(df)

In [35]:
df["Illegal"].value_counts()

Illegal
0    655
3    278
4    240
2    212
5    188
1    176
6    136
Name: count, dtype: int64

In [36]:
#inhalants (amyl, VSA)
df["Inhalants"] = None
def calculate_inhalants(df):
    for index, row in df.iterrows():
        amyl = int(row["Amyl"])
        vsa = int(row["VSA"])
        df.loc[index, "Inhalants"] = max(amyl, vsa)

calculate_inhalants(df)

In [37]:
df["Inhalants"].value_counts()

Inhalants
0    1082
2     313
1     280
3     140
4      34
5      26
6      10
Name: count, dtype: int64

In [38]:
df

,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Alcohol,Amphet,Amyl,Benzos,Caff,Cannabis,Choc,Coke,Crack,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,Semer,VSA,Soft,Prescription,Stims,HardStims,Downers,HardDowners,Psychs,Legal,Illegal,Inhalants
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084,5,2,0,2,6,0,5,0,0,0,0,0,0,0,0,0,2,0,0,6,2,6,2,5,2,0,6,0,0
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,-0.14277,-0.71126,-0.21575,5,2,2,0,6,4,6,3,0,4,0,2,0,2,3,0,4,0,0,6,2,6,4,5,2,2,6,4,2
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,-1.37983,0.40148,6,0,0,0,6,3,4,0,0,0,0,0,0,0,0,1,0,0,0,6,0,6,0,6,0,1,6,1,0
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,0.58489,-1.37983,-1.18084,4,0,0,3,5,2,4,2,0,0,0,2,0,0,0,0,2,0,0,5,3,5,2,4,3,2,5,2,0
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,1.30612,-0.21712,-0.21575,4,1,1,0,6,3,6,0,0,1,0,0,1,0,0,2,2,0,0,6,1,6,1,4,0,2,6,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,1884,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,-1.13788,0.88113,1.92173,5,0,0,0,4,5,4,0,0,0,0,0,3,3,0,0,0,0,5,5,0,4,0,5,0,3,5,3,5
1881,1885,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,-1.51840,0.88113,0.76540,5,0,0,0,5,3,4,0,0,2,0,0,3,5,4,4,5,0,0,5,0,5,4,5,0,5,5,5,0
1882,1886,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,-1.38502,0.52975,-0.52593,4,6,5,5,6,6,6,4,0,4,0,2,0,2,0,2,6,0,0,6,6,6,6,5,5,2,6,4,5
1883,1887,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,-2.57309,1.29221,1.22470,5,0,0,0,6,6,5,0,0,3,0,0,3,3,0,3,4,0,0,6,0,6,3,5,0,3,6,3,0
1884,1888,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,0.41594,0.88113,1.22470,4,3,0,3,6,3,6,3,0,3,0,0,3,3,0,3,6,0,2,6,3,6,3,4,3,3,6,3,2

In [39]:
df.drop(columns = "Choc", inplace = True)

In [40]:
df

,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Alcohol,Amphet,Amyl,Benzos,Caff,Cannabis,Coke,Crack,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,Semer,VSA,Soft,Prescription,Stims,HardStims,Downers,HardDowners,Psychs,Legal,Illegal,Inhalants
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084,5,2,0,2,6,0,0,0,0,0,0,0,0,0,0,2,0,0,6,2,6,2,5,2,0,6,0,0
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,-0.14277,-0.71126,-0.21575,5,2,2,0,6,4,3,0,4,0,2,0,2,3,0,4,0,0,6,2,6,4,5,2,2,6,4,2
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,-1.37983,0.40148,6,0,0,0,6,3,0,0,0,0,0,0,0,0,1,0,0,0,6,0,6,0,6,0,1,6,1,0
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,0.58489,-1.37983,-1.18084,4,0,0,3,5,2,2,0,0,0,2,0,0,0,0,2,0,0,5,3,5,2,4,3,2,5,2,0
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,1.30612,-0.21712,-0.21575,4,1,1,0,6,3,0,0,1,0,0,1,0,0,2,2,0,0,6,1,6,1,4,0,2,6,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,1884,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,-1.13788,0.88113,1.92173,5,0,0,0,4,5,0,0,0,0,0,3,3,0,0,0,0,5,5,0,4,0,5,0,3,5,3,5
1881,1885,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,-1.51840,0.88113,0.76540,5,0,0,0,5,3,0,0,2,0,0,3,5,4,4,5,0,0,5,0,5,4,5,0,5,5,5,0
1882,1886,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,-1.38502,0.52975,-0.52593,4,6,5,5,6,6,4,0,4,0,2,0,2,0,2,6,0,0,6,6,6,6,5,5,2,6,4,5
1883,1887,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,-2.57309,1.29221,1.22470,5,0,0,0,6,6,0,0,3,0,0,3,3,0,3,4,0,0,6,0,6,3,5,0,3,6,3,0
1884,1888,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,0.41594,0.88113,1.22470,4,3,0,3,6,3,3,0,3,0,0,3,3,0,3,6,0,2,6,3,6,3,4,3,3,6,3,2

In [41]:
df = df[df['Semer'] == "0"]

In [42]:
df.drop(columns = ["Semer"])

,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Alcohol,Amphet,Amyl,Benzos,Caff,Cannabis,Coke,Crack,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,VSA,Soft,Prescription,Stims,HardStims,Downers,HardDowners,Psychs,Legal,Illegal,Inhalants
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084,5,2,0,2,6,0,0,0,0,0,0,0,0,0,0,2,0,6,2,6,2,5,2,0,6,0,0
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,-0.14277,-0.71126,-0.21575,5,2,2,0,6,4,3,0,4,0,2,0,2,3,0,4,0,6,2,6,4,5,2,2,6,4,2
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,-1.37983,0.40148,6,0,0,0,6,3,0,0,0,0,0,0,0,0,1,0,0,6,0,6,0,6,0,1,6,1,0
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,0.58489,-1.37983,-1.18084,4,0,0,3,5,2,2,0,0,0,2,0,0,0,0,2,0,5,3,5,2,4,3,2,5,2,0
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,1.30612,-0.21712,-0.21575,4,1,1,0,6,3,0,0,1,0,0,1,0,0,2,2,0,6,1,6,1,4,0,2,6,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,1884,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,-1.13788,0.88113,1.92173,5,0,0,0,4,5,0,0,0,0,0,3,3,0,0,0,5,5,0,4,0,5,0,3,5,3,5
1881,1885,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,-1.51840,0.88113,0.76540,5,0,0,0,5,3,0,0,2,0,0,3,5,4,4,5,0,5,0,5,4,5,0,5,5,5,0
1882,1886,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,-1.38502,0.52975,-0.52593,4,6,5,5,6,6,4,0,4,0,2,0,2,0,2,6,0,6,6,6,6,5,5,2,6,4,5
1883,1887,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,-2.57309,1.29221,1.22470,5,0,0,0,6,6,0,0,3,0,0,3,3,0,3,4,0,6,0,6,3,5,0,3,6,3,0
1884,1888,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,0.41594,0.88113,1.22470,4,3,0,3,6,3,3,0,3,0,0,3,3,0,3,6,2,6,3,6,3,4,3,3,6,3,2

In [43]:
replacement_age= {
    -0.95197: '18 - 24',
    -0.07854: '25 - 34',
    0.49788: '35 - 44',
    1.09449: '45 - 54',
    1.82213: '55 - 64',
    2.59171: '65+'
}

df['Age']= df['Age'].replace(replacement_age)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\4216670211.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']= df['Age'].replace(replacement_age)

In [44]:
df["Age"].value_counts()

Age
18 - 24    637
25 - 34    480
35 - 44    355
45 - 54    294
55 - 64     93
65+         18
Name: count, dtype: int64

In [45]:
replacement_gender = {
    0.48246 : "F",
    -0.48246 : "M"}
df["Gender"] = df["Gender"].replace(replacement_gender)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\3352165843.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].replace(replacement_gender)

In [46]:
df["Gender"].value_counts()

Gender
M    940
F    937
Name: count, dtype: int64

In [47]:
replacement_education = {
    -2.43591: "Left before 16",
    -1.73790: "Left at 16",
    -1.43719: "Left at 17",
    -1.22751: "Left at 18",
    -0.61113: "Some College",
    -0.05921: "Professional Certificate",
    0.45468: "University Degree",
    1.16365: "Masters Degree",
    1.98437: "Doctorate Degree"
}
df["Education"] = df["Education"].replace(replacement_education)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\173153865.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Education"] = df["Education"].replace(replacement_education)

In [48]:
df["Education"].value_counts()

Education
Some College                503
University Degree           478
Masters Degree              283
Professional Certificate    270
Left at 18                   99
Left at 16                   98
Doctorate Degree             89
Left at 17                   29
Left before 16               28
Name: count, dtype: int64

In [49]:
replacement_country = {
    -0.09765: "Australia",
    0.24923: "Canada",
    -0.46841: "New Zealand",
    -0.28519: "Other",
    0.21128: "Republic of Ireland",
    0.96082: "UK",
    -0.57009: "USA"
    
}
df["Country"] = df["Country"].replace(replacement_country)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\1055650603.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Country"] = df["Country"].replace(replacement_country)

In [50]:
df["Country"].value_counts()

Country
UK                     1044
USA                     551
Other                   118
Canada                   87
Australia                52
Republic of Ireland      20
New Zealand               5
Name: count, dtype: int64

In [51]:
replacment_ethnicity = {
    -0.50212: "Asian",
    -1.10702: "Black",
    1.90725: "Mixed-Black/Asian",
    0.12600: "Mixed-White/Asian",
    -0.22166: "Mixed-White/Black",
    0.11440: "Other",
    -0.31685: "White"
    
}
df["Ethnicity"] = df["Ethnicity"].replace(replacment_ethnicity)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\1358832290.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Ethnicity"] = df["Ethnicity"].replace(replacment_ethnicity)

In [52]:
df["Ethnicity"].value_counts()

Ethnicity
White                1715
Other                  62
Black                  33
Asian                  25
Mixed-White/Asian      20
Mixed-White/Black      19
Mixed-Black/Asian       3
Name: count, dtype: int64

In [53]:
replacement_nscore = {
    -3.46436: 12,
    -1.32828: 24,
    0.04257: 36,
    1.23461: 48,
    -3.15735: 13,
    -1.19430: 25,
    0.13606: 37,
    1.37297: 49,
    -2.75696: 14,
    -1.05308: 26,
    0.22393: 38,
    1.49158: 50,
    -2.52197: 15,
    -0.92104: 27,
    0.31287: 39,
    1.60383: 51,
    -2.42317: 16,
    -0.79151: 28,
    0.41667: 40,
    1.72012: 52,
    -2.34360: 17,
    -0.67825: 29,
    0.52135: 41,
    1.83990: 53,
    -2.21844: 18,
    -0.58016: 30,
    0.62967: 42,
    1.98437: 54,
    -2.05048: 19,
    -0.46725: 31,
     0.73545: 43,
    2.12700: 55,
    -1.86962: 20,
    -0.34799: 32,
    0.82562: 44,
    2.28554: 56,
    -1.69163: 21,
    -0.24649: 33,
    0.91093: 45,
    2.46262: 57,
    -1.55078: 22,
    -0.14882: 34,
    1.02119: 46,
    2.61139: 58,
    -1.43907: 23,
    -0.05188: 35,
    1.13281: 47,
    2.82196: 59,
    3.27393: 60
}

df['Nscore'] = df['Nscore'].replace(replacement_nscore)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\648865101.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Nscore'] = df['Nscore'].replace(replacement_nscore)

In [54]:
df['Nscore'].value_counts()

Nscore
31.0    86
40.0    80
32.0    77
42.0    77
34.0    76
36.0    73
28.0    70
35.0    69
37.0    67
46.0    67
33.0    67
39.0    66
27.0    65
38.0    62
41.0    61
30.0    60
29.0    59
26.0    57
25.0    56
44.0    51
43.0    49
48.0    48
49.0    40
45.0    37
24.0    35
21.0    31
23.0    29
47.0    27
51.0    27
22.0    26
20.0    24
50.0    24
53.0    20
52.0    17
19.0    16
54.0    14
55.0    11
18.0    10
56.0    10
14.0     7
57.0     6
59.0     5
17.0     4
15.0     4
16.0     3
58.0     3
60.0     2
13.0     1
12.0     1
Name: count, dtype: int64

In [55]:
replacement_escore = {
    -3.27393: 16,
    -1.76250: 27,
    -0.30033: 38,
    1.45421: 49,
    -3.00537: 17,
    -1.63340: 28,
    -0.15487: 39,
    1.58487: 50,
    -3.00537: 18,
    -1.50796: 29,
    0.00332: 40,
    1.74091: 51,
    -2.72827: 19,
    -1.37639: 30,
    0.16767: 41,
    1.93886: 52,
    -2.53830: 20,
    -1.23177: 31,
    0.32197: 42,
    2.12700: 53,
    -2.44904: 21,
    -1.09207: 32,
    0.47617: 43,
    2.32338: 54,
    -2.32338: 22,
    -0.94779: 33,
    0.63779: 44,
    2.57309: 55,
    -2.21069: 23,
    -0.80615: 34,
    0.80523: 45,
    2.85950: 56,
    -2.11437: 24,
    -0.69509: 35,
    0.96248: 46,
    2.85950: 57,
    -2.03972: 25,
    -0.57545: 36,
    1.11406: 47,
    3.00537: 58,
    -1.92173: 26,
    -0.43999: 37,
    1.28610: 48,
    3.27393: 59
}
df['Escore'] = df['Escore'].replace(replacement_escore)
df['Escore'].value_counts()

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\2913870090.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Escore'] = df['Escore'].replace(replacement_escore)

Escore
40.0    130
41.0    116
42.0    108
39.0    107
38.0    105
43.0    105
44.0    103
45.0     90
37.0     90
36.0     89
33.0     77
46.0     69
34.0     66
47.0     63
48.0     61
35.0     58
31.0     55
32.0     52
30.0     38
49.0     37
51.0     33
29.0     32
50.0     25
27.0     23
28.0     23
52.0     21
26.0     21
53.0     15
54.0     10
55.0      9
24.0      9
22.0      8
19.0      6
23.0      5
25.0      4
20.0      3
21.0      3
16.0      2
57.0      2
59.0      2
58.0      1
18.0      1
Name: count, dtype: int64

In [56]:
replacement_oscore = {
    -3.27393: 24,
    -1.11902: 38,
    0.58331: 50,
    -2.85950: 26,
    -0.97631: 39,
    0.72330: 51,
    -2.63199: 28,
    -0.84732: 40,
    0.88309: 52,
    -2.39883: 29,
    -0.71727: 41,
    1.06238: 53,
    -2.21069: 30,
    -0.58331: 42,
    1.24033: 54,
    -2.09015: 31,
    -0.45174: 43,
    1.43533: 55,
    -1.97495: 32,
    -0.31776: 44,
    1.65653: 56,
    -1.82919: 33,
    -0.17779: 45,
    1.88511: 57,
    -1.68062: 34,
    -0.01928: 46,
    1.15324: 58,
    -1.55521: 35,
    0.14143: 47,
    2.44904: 59,
    -1.42424: 36,
    0.29338: 48,
    2.90161: 60,
    -1.27553: 37,
    0.44585: 49
}

df['Oscore'] = df['Oscore'].replace(replacement_oscore)
df['Oscore'].value_counts()

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\715536436.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Oscore'] = df['Oscore'].replace(replacement_oscore)

Oscore
46.00000    134
48.00000    115
47.00000    106
45.00000    103
44.00000    101
49.00000     98
42.00000     87
51.00000     86
43.00000     86
52.00000     86
50.00000     83
53.00000     79
41.00000     76
40.00000     68
38.00000     64
55.00000     63
39.00000     60
54.00000     57
37.00000     50
36.00000     39
56.00000     38
57.00000     34
35.00000     26
34.00000     25
33.00000     23
2.15324      18
59.00000     13
32.00000     13
29.00000     11
31.00000      9
30.00000      9
60.00000      7
26.00000      4
28.00000      4
24.00000      2
Name: count, dtype: int64

In [57]:
df['Oscore'] = df['Oscore'].replace(2.15324, 58.00000)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\2747326202.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Oscore'] = df['Oscore'].replace(2.15324, 58.00000)

In [58]:
df['Oscore'].value_counts()

Oscore
46.0    134
48.0    115
47.0    106
45.0    103
44.0    101
49.0     98
42.0     87
51.0     86
43.0     86
52.0     86
50.0     83
53.0     79
41.0     76
40.0     68
38.0     64
55.0     63
39.0     60
54.0     57
37.0     50
36.0     39
56.0     38
57.0     34
35.0     26
34.0     25
33.0     23
58.0     18
59.0     13
32.0     13
29.0     11
31.0      9
30.0      9
60.0      7
26.0      4
28.0      4
24.0      2
Name: count, dtype: int64

In [59]:
replacement_ascore = {
    -3.46436: 12,
    -1.34289: 34,
    0.76096: 48,
    -3.15735: 16,
    -1.21213: 35,
    0.94156: 49,
    -3.00537: 18,
    -1.07533: 36,
    1.11406: 50,
    -2.90161: 23,
    -0.91699: 37,
    1.28610: 51,
    -2.78793: 24,
    -0.76096: 38,
    1.45039: 52,
    -2.70172: 25,
    -0.60633: 39,
    1.61108: 53,
    -2.53830: 26,
    -0.45321: 40,
    1.81866: 54,
    -2.35413: 27,
    -0.30172: 41,
    2.03972: 55,
    -2.21844: 28,
    -0.15487: 42,
    2.23427: 56,
    -2.07848: 29,
    -0.01729: 43,
    2.46262: 57,
    -1.92595: 30,
    0.13136: 44,
    2.75696: 58,
    -1.77200: 31,
    0.28783: 45,
    3.15735: 59,
    -1.62090: 32,
    0.43852: 46,
    3.46436: 60,
    -1.47955: 33,
    0.59042: 47,
    0.76096: 48,
    0.94156: 49,
    1.11406: 50,
    1.28610: 51,
    1.45039: 52,
    1.61108: 53,
    1.81866: 54,
    2.03972: 55,
    2.23427: 56,
    2.46262: 57,
    2.75696: 58,
    3.15735: 59,
    3.46436: 60
}

df['Ascore'] = df['Ascore'].replace(replacement_ascore)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\2558000847.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ascore'] = df['Ascore'].replace(replacement_ascore)

In [60]:
df['Ascore'].value_counts()

Ascore
44.0    117
41.0    114
45.0    112
43.0    104
48.0    103
42.0    101
39.0    101
47.0    100
46.0    100
40.0     98
49.0     85
37.0     83
38.0     82
50.0     68
36.0     62
51.0     57
35.0     45
34.0     41
52.0     39
54.0     36
53.0     36
33.0     33
32.0     30
31.0     24
30.0     18
55.0     15
56.0     14
29.0     13
57.0      8
28.0      8
26.0      7
58.0      7
27.0      7
24.0      2
16.0      1
18.0      1
12.0      1
23.0      1
59.0      1
25.0      1
60.0      1
Name: count, dtype: int64

In [61]:
replacement_cscore = {
    -3.46436: 17,
    -1.25773: 32,
    0.58489: 46,
    -3.15735: 19,
    -1.13788: 33,
    0.7583: 47,
    -2.90161: 20,
    -1.01450: 34,
    0.93949: 48,
    -2.72827: 21,
    -0.89891: 35,
    1.13407: 49,
    -2.57309: 22,
    -0.78155: 36,
    1.30612: 50,
    -2.42317: 23,
    -0.65253: 37,
    1.46191: 51,
    -2.30408: 24,
    -0.52745: 38,
    1.63088: 52,
    -2.18109: 25,
    -0.40581: 39,
    1.81175: 53,
    -2.04506: 26,
    -0.27607: 40,
    2.04506: 54,
    -1.92173: 27,
    -0.14277: 41,
    2.33337: 55,
    -1.78169: 28,
    -0.00665: 42,
    2.63199: 56,
    -1.64101: 29,
    0.12331: 43,
    3.00537: 57,
    -1.51840: 30,
    0.25953: 44,
    3.46436: 59,
    -1.38502: 31,
    0.41594: 45
}
df["Cscore"] = df["Cscore"].replace(replacement_cscore)
df["Cscore"].value_counts()

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\970079738.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Cscore"] = df["Cscore"].replace(replacement_cscore)

Cscore
46.0    113
44.0    111
45.0    110
42.0    103
41.0     99
40.0     97
47.0     95
48.0     95
43.0     88
39.0     87
37.0     81
38.0     76
49.0     76
36.0     69
35.0     55
34.0     55
33.0     49
50.0     47
51.0     43
31.0     41
32.0     39
52.0     34
30.0     29
54.0     27
53.0     27
28.0     25
29.0     24
55.0     13
26.0     13
27.0     12
25.0      9
56.0      8
24.0      6
22.0      5
23.0      5
20.0      3
57.0      3
21.0      2
59.0      1
19.0      1
17.0      1
Name: count, dtype: int64

In [62]:
replacememt_impulsive = {
    -2.55524: 0.0106,
    -1.37983: 0.1464,
    -0.71126: 0.1629,
    -0.21712: 0.1883,
    0.19268:  0.1363,
    0.52975: 0.1146,
    0.88113: 0.1034,
    1.29221: 0.0785,
    1.86203: 0.0552,
    2.90161: 0.0037
}
df["Impulsive"] = df["Impulsive"].replace(replacememt_impulsive)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\3440545917.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Impulsive"] = df["Impulsive"].replace(replacememt_impulsive)

In [63]:
df["Impulsive"].value_counts()

Impulsive
0.1883    355
0.1629    306
0.1464    275
0.1363    257
0.1146    215
0.1034    192
0.0785    146
0.0552    104
0.0106     20
0.0037      7
Name: count, dtype: int64

In [64]:
replacement_ss = {
    -2.07848: 0.0377,
    -1.54858: 0.0462,
    -1.18084: 0.0700,
    -0.84637: 0.0897,
    -0.52593: 0.1119,
    -0.21575: 0.1183,
    0.07987: 0.1162,
    0.40148: 0.1321,
    0.76540: 0.1119,
    1.22470: 0.1114,
    1.92173: 0.0546
}
df["SS"] = df["SS"].replace(replacement_ss)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\3095521364.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["SS"] = df["SS"].replace(replacement_ss)

In [65]:
df.drop(columns = ["Semer"], inplace = True)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\443197215.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns = ["Semer"], inplace = True)

In [66]:
df_i = df[["ID", "Age", "Gender", "Education", "Country", "Ethnicity", "Nscore", "Escore", "Oscore", "Ascore", "Cscore", "Impulsive", "SS", "Soft", "Prescription", "Stims", "HardStims", "Downers", "HardDowners", "Psychs", "Legal", "Illegal", "Inhalants"]]

In [67]:
df_i[["Soft", "Prescription", "Stims", "HardStims", "Downers", "HardDowners", "Psychs", "Legal", "Illegal", "Inhalants"]] = df_i[["Soft", "Prescription", "Stims", "HardStims", "Downers", "HardDowners", "Psychs", "Legal", "Illegal", "Inhalants"]].astype(int)

C:\Users\zaiid\AppData\Local\Temp\ipykernel_30360\3871418487.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_i[["Soft", "Prescription", "Stims", "HardStims", "Downers", "HardDowners", "Psychs", "Legal", "Illegal", "Inhalants"]] = df_i[["Soft", "Prescription", "Stims", "HardStims", "Downers", "HardDowners", "Psychs", "Legal", "Illegal", "Inhalants"]].astype(int)

In [68]:
df_i_dummies = pd.get_dummies(df_i)

In [69]:
df_i_dummies

,ID,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Soft,Prescription,Stims,HardStims,Downers,HardDowners,Psychs,Legal,Illegal,Inhalants,Age_18 - 24,Age_25 - 34,Age_35 - 44,Age_45 - 54,Age_55 - 64,Age_65+,Gender_F,Gender_M,Education_Doctorate Degree,Education_Left at 16,Education_Left at 17,Education_Left at 18,Education_Left before 16,Education_Masters Degree,Education_Professional Certificate,Education_Some College,Education_University Degree,Country_Australia,Country_Canada,Country_New Zealand,Country_Other,Country_Republic of Ireland,Country_UK,Country_USA,Ethnicity_Asian,Ethnicity_Black,Ethnicity_Mixed-Black/Asian,Ethnicity_Mixed-White/Asian,Ethnicity_Mixed-White/Black,Ethnicity_Other,Ethnicity_White
0,1,39.0,36.0,42.0,37.0,42.0,0.1883,0.0700,6,2,6,2,5,2,0,6,0,0,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
1,2,29.0,52.0,55.0,48.0,41.0,0.1629,0.1183,6,2,6,4,5,2,2,6,4,2,False,True,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
2,3,31.0,45.0,40.0,32.0,34.0,0.1464,0.1321,6,0,6,0,6,0,1,6,1,0,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
3,4,34.0,34.0,46.0,47.0,46.0,0.1464,0.0700,5,3,5,2,4,3,2,5,2,0,True,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
4,5,43.0,28.0,43.0,41.0,50.0,0.1883,0.1183,6,1,6,1,4,0,2,6,2,1,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,1884,25.0,51.0,57.0,48.0,33.0,0.1034,0.0546,5,0,4,0,5,0,3,5,3,5,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1881,1885,33.0,51.0,50.0,48.0,30.0,0.1034,0.1119,5,0,5,4,5,0,5,5,5,0,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1882,1886,47.0,30.0,37.0,31.0,31.0,0.1146,0.1119,6,6,6,6,5,5,2,6,4,5,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1883,1887,45.0,26.0,48.0,32.0,22.0,0.0785,0.1114,6,0,6,3,5,0,3,6,3,0,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1884,1888,31.0,53.0,56.0,50.0,45.0,0.1034,0.1114,6,3,6,3,4,3,3,6,3,2,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True

In [70]:
df_i_dummies = df_i_dummies.set_index('ID')

In [71]:
df_i_dummies

,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Soft,Prescription,Stims,HardStims,Downers,HardDowners,Psychs,Legal,Illegal,Inhalants,Age_18 - 24,Age_25 - 34,Age_35 - 44,Age_45 - 54,Age_55 - 64,Age_65+,Gender_F,Gender_M,Education_Doctorate Degree,Education_Left at 16,Education_Left at 17,Education_Left at 18,Education_Left before 16,Education_Masters Degree,Education_Professional Certificate,Education_Some College,Education_University Degree,Country_Australia,Country_Canada,Country_New Zealand,Country_Other,Country_Republic of Ireland,Country_UK,Country_USA,Ethnicity_Asian,Ethnicity_Black,Ethnicity_Mixed-Black/Asian,Ethnicity_Mixed-White/Asian,Ethnicity_Mixed-White/Black,Ethnicity_Other,Ethnicity_White
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,39.0,36.0,42.0,37.0,42.0,0.1883,0.0700,6,2,6,2,5,2,0,6,0,0,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
2,29.0,52.0,55.0,48.0,41.0,0.1629,0.1183,6,2,6,4,5,2,2,6,4,2,False,True,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
3,31.0,45.0,40.0,32.0,34.0,0.1464,0.1321,6,0,6,0,6,0,1,6,1,0,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
4,34.0,34.0,46.0,47.0,46.0,0.1464,0.0700,5,3,5,2,4,3,2,5,2,0,True,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
5,43.0,28.0,43.0,41.0,50.0,0.1883,0.1183,6,1,6,1,4,0,2,6,2,1,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1884,25.0,51.0,57.0,48.0,33.0,0.1034,0.0546,5,0,4,0,5,0,3,5,3,5,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1885,33.0,51.0,50.0,48.0,30.0,0.1034,0.1119,5,0,5,4,5,0,5,5,5,0,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1886,47.0,30.0,37.0,31.0,31.0,0.1146,0.1119,6,6,6,6,5,5,2,6,4,5,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1887,45.0,26.0,48.0,32.0,22.0,0.0785,0.1114,6,0,6,3,5,0,3,6,3,0,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1888,31.0,53.0,56.0,50.0,45.0,0.1034,0.1114,6,3,6,3,4,3,3,6,3,2,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True

In [72]:
features = df_i_dummies.drop(columns = ["Soft", "Prescription", "Stims", "HardStims", "Downers", "HardDowners", "Psychs", "Legal", "Illegal", "Inhalants"])
target = df_i_dummies[["Soft", "Prescription", "Stims", "HardStims", "Downers", "HardDowners", "Psychs", "Legal", "Illegal", "Inhalants"]]

In [73]:
features

,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Age_18 - 24,Age_25 - 34,Age_35 - 44,Age_45 - 54,Age_55 - 64,Age_65+,Gender_F,Gender_M,Education_Doctorate Degree,Education_Left at 16,Education_Left at 17,Education_Left at 18,Education_Left before 16,Education_Masters Degree,Education_Professional Certificate,Education_Some College,Education_University Degree,Country_Australia,Country_Canada,Country_New Zealand,Country_Other,Country_Republic of Ireland,Country_UK,Country_USA,Ethnicity_Asian,Ethnicity_Black,Ethnicity_Mixed-Black/Asian,Ethnicity_Mixed-White/Asian,Ethnicity_Mixed-White/Black,Ethnicity_Other,Ethnicity_White
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,39.0,36.0,42.0,37.0,42.0,0.1883,0.0700,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
2,29.0,52.0,55.0,48.0,41.0,0.1629,0.1183,False,True,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
3,31.0,45.0,40.0,32.0,34.0,0.1464,0.1321,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
4,34.0,34.0,46.0,47.0,46.0,0.1464,0.0700,True,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
5,43.0,28.0,43.0,41.0,50.0,0.1883,0.1183,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1884,25.0,51.0,57.0,48.0,33.0,0.1034,0.0546,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1885,33.0,51.0,50.0,48.0,30.0,0.1034,0.1119,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1886,47.0,30.0,37.0,31.0,31.0,0.1146,0.1119,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1887,45.0,26.0,48.0,32.0,22.0,0.0785,0.1114,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1888,31.0,53.0,56.0,50.0,45.0,0.1034,0.1114,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True

In [74]:
target

,Soft,Prescription,Stims,HardStims,Downers,HardDowners,Psychs,Legal,Illegal,Inhalants
ID,,,,,,,,,,
1,6,2,6,2,5,2,0,6,0,0
2,6,2,6,4,5,2,2,6,4,2
3,6,0,6,0,6,0,1,6,1,0
4,5,3,5,2,4,3,2,5,2,0
5,6,1,6,1,4,0,2,6,2,1
...,...,...,...,...,...,...,...,...,...,...
1884,5,0,4,0,5,0,3,5,3,5
1885,5,0,5,4,5,0,5,5,5,0
1886,6,6,6,6,5,5,2,6,4,5
1887,6,0,6,3,5,0,3,6,3,0
1888,6,3,6,3,4,3,3,6,3,2

In [75]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [76]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [77]:
random_forest = RandomForestClassifier()

In [78]:
random_forest.fit(X_train, y_train)

RandomForestClassifier()

In [79]:

y_pred = random_forest.predict(X_test)

In [80]:
y_pred

array([[6, 2, 6, ..., 6, 2, 1],
       [6, 0, 6, ..., 6, 0, 0],
       [6, 6, 6, ..., 6, 3, 0],
       ...,
       [6, 0, 6, ..., 6, 4, 0],
       [6, 0, 6, ..., 6, 0, 0],
       [6, 2, 6, ..., 6, 4, 0]])

In [81]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [82]:
from sklearn.metrics import accuracy_score
import numpy as np

In [83]:
output_accuracies = []

# Convert y_test and y_pred to arrays
y_test_array = np.array(y_test)
y_pred_array = np.array(y_pred)

# Calculate accuracy for each output dimension
for i in range(y_test_array.shape[1]):
    accuracy = accuracy_score(y_test_array[:, i], y_pred_array[:, i])
    output_accuracies.append(accuracy)

# Calculate the average accuracy across all output dimensions
print(output_accuracies)
average_accuracy = sum(output_accuracies) / len(output_accuracies)
print("Average Accuracy:", average_accuracy)

[0.8617021276595744, 0.4308510638297872, 0.773936170212766, 0.4148936170212766, 0.39095744680851063, 0.4946808510638298, 0.5186170212765957, 0.8324468085106383, 0.43351063829787234, 0.5611702127659575]
Average Accuracy: 0.5712765957446808

In [84]:
from sklearn.preprocessing import MinMaxScaler

In [85]:
norm = MinMaxScaler()

In [86]:
norm.fit(X_train)

MinMaxScaler()

In [87]:
X_train_norm = norm.transform(X_train)

X_test_norm = norm.transform(X_test)

In [88]:
X_train_norm = pd.DataFrame(X_train_norm, columns = X_train.columns)
X_test_norm = pd.DataFrame(X_test_norm, columns = X_test.columns)

In [89]:
random_forest.fit(X_train_norm, y_train)

RandomForestClassifier()

In [90]:
y_pred_norm = random_forest.predict(X_test_norm)

In [91]:
# Calculate accuracy for each output dimension
output_accuracies = []
for i in range(y_test.shape[1]):
    accuracy = accuracy_score(y_test.iloc[:, i], y_pred_norm[:, i])
    output_accuracies.append(accuracy)

# Calculate the average accuracy across all output dimensions
average_accuracy = sum(output_accuracies) / len(output_accuracies)
print("Output Accuracies:", output_accuracies)
print("Average Accuracy:", average_accuracy)

Output Accuracies: [0.8643617021276596, 0.42819148936170215, 0.773936170212766, 0.43617021276595747, 0.3803191489361702, 0.4920212765957447, 0.5026595744680851, 0.8351063829787234, 0.425531914893617, 0.5558510638297872]
Average Accuracy: 0.5694148936170212

In [92]:
target.shape

(1877, 10)

In [93]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import make_scorer, accuracy_score
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MinMaxScaler

# Convert y_train and y_test to numpy arrays
y_train_array = y_train.values if isinstance(y_train, pd.DataFrame) else y_train
y_test_array = y_test.values if isinstance(y_test, pd.DataFrame) else y_test

# Define the model
base_rf = RandomForestClassifier(random_state=42)
model = MultiOutputClassifier(base_rf)

# Define the hyperparameter grid
param_grid = {
    'estimator__n_estimators': [100, 200, 500],
    'estimator__max_depth': [None, 10, 20],
    'estimator__min_samples_split': [2, 5, 10],
    'estimator__min_samples_leaf': [1, 2, 4]
}

# Define a custom scorer
def multioutput_accuracy(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    accuracies = []
    for i in range(y_true.shape[1]):
        accuracies.append(accuracy_score(y_true[:, i], y_pred[:, i]))
    return np.mean(accuracies)

scorer = make_scorer(multioutput_accuracy, greater_is_better=True)

# Setup the grid search
grid_search = GridSearchCV(model, param_grid, scoring=scorer, cv=3, verbose=2, n_jobs=-1)

# Perform the grid search
grid_search.fit(X_train_norm, y_train_array)

# Print the best hyperparameters
print("Best hyperparameters found: ", grid_search.best_params_)

# Evaluate the best model on the test set
best_model = grid_search.best_estimator_
y_pred_test = best_model.predict(X_test_norm)

# Calculate and print the average accuracy for the test set
test_accuracies = []
for i in range(y_test_array.shape[1]):
    test_accuracies.append(accuracy_score(y_test_array[:, i], y_pred_test[:, i]))

average_test_accuracy = np.mean(test_accuracies)
print("Average Test Accuracy:", average_test_accuracy)

Fitting 3 folds for each of 81 candidates, totalling 243 fits
Best hyperparameters found:  {'estimator__max_depth': 10, 'estimator__min_samples_leaf': 2, 'estimator__min_samples_split': 10, 'estimator__n_estimators': 100}
Average Test Accuracy: 0.5819148936170213

In [94]:
target_granular = df[["Alcohol", "Amphet", "Amyl", "Benzos", "Caff", "Cannabis", "Coke", "Crack", "Ecstasy", "Heroin", "Ketamine", "Legalh", "LSD", "Meth", "Mushrooms", "Nicotine", "VSA"]]

In [95]:
X_train, X_test, y_train, y_test = train_test_split(features, target_granular, test_size=0.2, random_state=42)

In [96]:
random_forest.fit(X_train, y_train)

RandomForestClassifier()

In [97]:
y_pred = random_forest.predict(X_test)

In [98]:
y_pred

array([['5', '1', '0', ..., '0', '6', '0'],
       ['5', '0', '0', ..., '0', '2', '0'],
       ['6', '0', '0', ..., '2', '6', '0'],
       ...,
       ['5', '0', '0', ..., '3', '6', '0'],
       ['5', '0', '0', ..., '0', '0', '0'],
       ['6', '0', '0', ..., '2', '6', '0']], dtype=object)

In [99]:
output_accuracies = []

# Convert y_test and y_pred to arrays
y_test_array = np.array(y_test)
y_pred_array = np.array(y_pred)

# Calculate accuracy for each output dimension
for i in range(y_test_array.shape[1]):
    accuracy = accuracy_score(y_test_array[:, i], y_pred_array[:, i])
    output_accuracies.append(accuracy)

# Calculate the average accuracy across all output dimensions
print(output_accuracies)
average_accuracy = sum(output_accuracies) / len(output_accuracies)
print("Average Accuracy:", average_accuracy)

[0.36436170212765956, 0.5425531914893617, 0.6781914893617021, 0.5558510638297872, 0.7632978723404256, 0.40691489361702127, 0.5957446808510638, 0.8670212765957447, 0.5797872340425532, 0.8643617021276596, 0.8164893617021277, 0.6382978723404256, 0.6542553191489362, 0.7632978723404256, 0.5531914893617021, 0.3723404255319149, 0.7792553191489362]
Average Accuracy: 0.6350125156445556

In [100]:
norm.fit(X_train)

MinMaxScaler()

In [101]:
X_train_norm = norm.transform(X_train)

X_test_norm = norm.transform(X_test)

In [102]:
X_train_norm = pd.DataFrame(X_train_norm, columns = X_train.columns)
X_test_norm = pd.DataFrame(X_test_norm, columns = X_test.columns)

In [103]:
random_forest.fit(X_train_norm, y_train)

RandomForestClassifier()

In [104]:
y_pred_norm = random_forest.predict(X_test_norm)

In [105]:
# Calculate accuracy for each output dimension
output_accuracies = []
for i in range(y_test.shape[1]):
    accuracy = accuracy_score(y_test.iloc[:, i], y_pred_norm[:, i])
    output_accuracies.append(accuracy)

# Calculate the average accuracy across all output dimensions
average_accuracy = sum(output_accuracies) / len(output_accuracies)
print("Output Accuracies:", output_accuracies)
print("Average Accuracy:", average_accuracy)

Output Accuracies: [0.3776595744680851, 0.5212765957446809, 0.6941489361702128, 0.5531914893617021, 0.7632978723404256, 0.4015957446808511, 0.5957446808510638, 0.8723404255319149, 0.5771276595744681, 0.8643617021276596, 0.8164893617021277, 0.6382978723404256, 0.6276595744680851, 0.7659574468085106, 0.5771276595744681, 0.375, 0.773936170212766]
Average Accuracy: 0.6350125156445556

In [106]:
# Convert y_train and y_test to numpy arrays
y_train_array = y_train.values if isinstance(y_train, pd.DataFrame) else y_train
y_test_array = y_test.values if isinstance(y_test, pd.DataFrame) else y_test

# Define the model
base_rf = RandomForestClassifier(random_state=42)
model = MultiOutputClassifier(base_rf)

# Define the hyperparameter grid
param_grid = {
    'estimator__n_estimators': [100, 200, 500],
    'estimator__max_depth': [None, 10, 20],
    'estimator__min_samples_split': [2, 5, 10],
    'estimator__min_samples_leaf': [1, 2, 4]
}

# Define a custom scorer
def multioutput_accuracy(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    accuracies = []
    for i in range(y_true.shape[1]):
        accuracies.append(accuracy_score(y_true[:, i], y_pred[:, i]))
    return np.mean(accuracies)

scorer = make_scorer(multioutput_accuracy, greater_is_better=True)

# Setup the grid search
grid_search = GridSearchCV(model, param_grid, scoring=scorer, cv=3, verbose=2, n_jobs=-1)

# Perform the grid search
grid_search.fit(X_train_norm, y_train_array)

# Print the best hyperparameters
print("Best hyperparameters found: ", grid_search.best_params_)

# Evaluate the best model on the test set
best_model = grid_search.best_estimator_
y_pred_test = best_model.predict(X_test_norm)

# Calculate and print the average accuracy for the test set
test_accuracies = []
for i in range(y_test_array.shape[1]):
    test_accuracies.append(accuracy_score(y_test_array[:, i], y_pred_test[:, i]))

average_test_accuracy = np.mean(test_accuracies)
print("Average Test Accuracy:", average_test_accuracy)

Fitting 3 folds for each of 81 candidates, totalling 243 fits
Best hyperparameters found:  {'estimator__max_depth': None, 'estimator__min_samples_leaf': 4, 'estimator__min_samples_split': 2, 'estimator__n_estimators': 100}
Average Test Accuracy: 0.642991239048811